# Generated by Django 3.1.4 on 2021-01-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0003_auto_20210110_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dl.gallery'),
            preserve_default=False,
        ),
    ]
